const CARDS_VERSION = '1.0.0';

function urlGif(root, name) {
  return `https://raw.githubusercontent.com/GIGIsOtherStuff/MRNGmedia/main/Media/CardImages/${root}/${name}.gif`;
}
function urlImg(root, name) {
  return `https://raw.githubusercontent.com/GIGIsOtherStuff/MRNGmedia/main/Media/CardImages/${root}/${name}.png`;
}


function GetCards() {
  return [
    {
      id: 1,
      img: urlImg('commons', 'quandaleDingle'),
      chance: '1 in 5',
      rarity: 'Common',
      title: "Quandale Dingle",
      desc: "I've been arrested for multiple crimes",
      discovered: false,
    },
    {
      id: 2,
      img: urlImg('commons', 'sakura'),
      chance: '1 in 10',
      rarity: 'Common',
      title: "Sakura",
      desc: "Shannaroo!",
      discovered: false,
    },
    {
      id: 3,
      img: urlImg('commons', 'bigDrandy'),
      chance: '1 in 15',
      rarity: 'Common',
      title: "Big Randy",
      desc: "On halloween..",
      discovered: false,
    },
    {
      id: 4,
      img: urlImg('commons', 'pepe'),
      chance: '1 in 20',
      rarity: 'Common',
      title: "Pepe",
      desc: "*Dead blind stare*",
      discovered: false,
    },
    {
      id: 5,
      img: urlImg('commons', 'steve'),
      chance: '1 in 26',
      rarity: 'Common',
      title: "Steve",
      desc: "Infinite power",
      discovered: false,
    },
    {
      id: 6,
      img: urlImg('commons', 'granny'),
      chance: '1 in 31',
      rarity: 'Common',
      title: "Granny",
      desc: "I see you!",
      discovered: false,
    },
    {
      id: 7,
      img: urlImg('commons', 'sherk'),
      chance: '1 in 37',
      rarity: 'Common',
      title: "Shrek",
      desc: "Better out than in, I always say.",
      discovered: false,
    },
    {
      id: 8,
      img: urlImg('commons', 'doge'),
      chance: '1 in 42',
      rarity: 'Common',
      title: "Doge",
      desc: "So doge, much wow",
      discovered: false,
    },
    {
      id: 9,
      img: urlImg('commons', 'spongebob'),
      chance: '1 in 50',
      rarity: 'Common',
      title: "Spongebob",
      desc: "Aye-aye, Captain!",
      discovered: false,
    },
    {
      id: 10,
      img: urlImg('rares', 'joeBartholozzi'),
      chance: '1 in 101',
      rarity: 'Rare',
      title: "Joe Barthalozzi",
      desc: "IM NOT DEAD MAN",
      discovered: false,
    },
    {
      id: 11,
      img: urlImg('rares', 'nyanCat'),
      chance: '1 in 120',
      rarity: 'Rare',
      title: "Nyan Cat",
      desc: "Nyan Nyan Nyan Nyan",
      discovered: false,
    },
    {
      id: 12,
      img: urlImg('rares', 'smurfCat'),
      chance: '1 in 142',
      rarity: 'Rare',
      title: "Smurf Cat",
      desc: "Du Du Dum Dum Dum",
      discovered: false,
    },
    {
      id: 13,
      img: urlImg('rares', 'patrick'),
      chance: '1 in 160',
      rarity: 'Rare',
      title: "Patrick Star",
      desc: "Is mayonnaise an instrument?",
      discovered: false,
    },
    {
      id: 14,
      img: urlImg('rares', 'adamSandler'),
      chance: '1 in 186',
      rarity: 'Rare',
      title: "Adam Sandler",
      desc: "It's cool, though.",
      discovered: false,
    },
    {
      id: 15,
      img: urlImg('rares', 'pikachu'),
      chance: '1 in 200',
      rarity: 'Rare',
      title: "Pikachu",
      desc: "Pika-Pi",
      discovered: false,
    },
    {
      id: 16,
      img: urlImg('rares', 'jason'),
      chance: '1 in 229',
      rarity: 'Rare',
      title: "Jason",
      desc: "Kill her, Mommy! Kill her!",
      discovered: false,
    },
    {
      id: 17,
      img: urlImg('rares', 'daBaby'),
      chance: '1 in 250',
      rarity: 'Rare',
      title: "Dababy",
      desc: "Lets Goo",
      discovered: false,
    },
    {
      id: 18,
      img: urlImg('rares', 'walterWhite'),
      chance: '1 in 277',
      rarity: 'Rare',
      title: "Walter White",
      desc: "Say my name..",
      discovered: false,
    },
    {
      id: 19,
      img: urlImg('rares', 'spiderman'),
      chance: '1 in 300',
      rarity: 'Rare',
      title: "Spiderman",
      desc: "My Spider-Sense is tingling",
      discovered: false,
    },
    {
      id: 20,
      img: urlImg('legendarys', 'yunoMiles'),
      chance: '1 in 600',
      rarity: 'Legendary',
      title: "Yuno Miles",
      desc: "Martin Luther had a DRE-E-E-EM",
      discovered: false,
    },
    {
      id: 21,
      img: urlImg('legendarys', 'david'),
      chance: '1 in 690', 
      rarity: 'Legendary',
      title: "David Baszuki",
      desc: "Focused on innovation",
      discovered: false,
    },
    {
      id: 22,
      img: urlImg('legendarys', 'professeur'),
      chance: '1 in 920',
      rarity: 'Legendary',
      title: "El Professeur",
      desc: "Next time do it yourself",
      discovered: false,
    },
    {
      id: 23,
      img: urlImg('legendarys', 'zestyDrake'),
      chance: '1 in 1200',
      rarity: 'Legendary',
      title: "Drake",
      desc: "Jeez louise",
      discovered: false,
    },
    {
      id: 24,
      img: urlImg('legendarys', 'elonMusk'),
      chance: '1 in 1450',
      rarity: 'Legendary',
      title: "Elon Musk",
      desc: "Mars coming soon!",
      discovered: false,
    },
    {
      id: 25,
      img: urlImg('legendarys', 'rickAstley'),
      chance: '1 in 1670',
      rarity: 'Legendary',
      title: "Rick Astley",
      desc: "Never gonna let you down",
      discovered: false,
    },
    {
      id: 26,
      img: urlImg('legendarys', 'gojo'),
      chance: '1 in 2000',
      rarity: 'Legendary',
      title: "Gojo",
      desc: "Nah, I'd win",
      discovered: false,
    },
    {
      id: 27,
      img: urlImg('legendarys', 'sigma'),
      chance: '1 in 2240',
      rarity: 'Legendary',
      title: "Sigma",
      desc: "Edge mogger",
      discovered: false,
    },
    {
      id: 28,
      img: urlImg('legendarys', 'djKhaled'),
      chance: '1 in 2500',
      rarity: 'Legendary',
      title: "DJ Khaled",
      desc: "Tell em' to bring out the whole ocean!",
      discovered: false,
    },
    {
      id: 29,
      img: urlImg('legendarys', 'joker'),
      chance: '1 in 2769',
      rarity: 'Legendary',
      title: "Joker",
      desc: "Let's put a smile on that face!",
      discovered: false,
    },
    {
      id: 30,
      img: urlGif('uniques', 'thanos'),
      chance: '1 in 6000',
      rarity: 'Unique',
      title: "Thanos",
      desc: "I am inevitable.",
      discovered: false,
    },
    {
      id: 31,
      img: urlGif('uniques', 'homelander'),
      chance: '1 in 6500', 
      rarity: 'Unique',
      title: "Homelander",
      desc: "The only one who possibly can..",
      discovered: false,
    },
    {
      id: 32,
      img: urlGif('uniques', 'kira'),
      chance: '1 in 7000',
      rarity: 'Unique',
      title: "Kira",
      desc: "THIS IS MY PERFECT VICTORY",
      discovered: false,
    },
    {
      id: 33,
      img: urlGif('uniques', 'zodd'),
      chance: '1 in 7500',
      rarity: 'Unique',
      title: "Nosferatu Zodd",
      desc: "Fight... Struggle... Death...",
      discovered: false,
    },
    {
      id: 34,
      img: urlGif('uniques', 'johnWick'),
      chance: '1 in 8000',
      rarity: 'Unique',
      title: "John Wick",
      desc: "I need a gun",
      discovered: false,
    },
    {
      id: 35,
      img: urlGif('uniques', 'venom'),
      chance: '1 in 8500', 
      rarity: 'Unique',
      title: "Venom",
      desc: "So many snacks, but so little time.",
      discovered: false,
    },
    {
      id: 36,
      img: urlGif('uniques', 'luffy'),
      chance: '1 in 9000',
      rarity: 'Unique',
      title: "Luffy",
      desc: "Gomu Gomu noo",
      discovered: false,
    },
    {
      id: 37,
      img: urlGif('supremes', 'poseidon'),
      chance: '1 in 11211',
      rarity: 'Supreme',
      title: "Poseidon",
      desc: "Tremble before my wrath!",
      discovered: false,
    },
    {
      id: 38,
      img: urlGif('supremes', 'zeus'),
      chance: '1 in 11211',
      rarity: 'Supreme',
      title: "Zeus",
      desc: "Done by my thunderbolt!",
      discovered: false,
    },
    {
      id: 39,
      img: urlGif('supremes', 'anubis'),
      chance: '1 in 11211',
      rarity: 'Supreme',
      title: "Anubis",
      desc: "I guide the dead to the afterlife",
      discovered: false,
    },
  ]
}

export default GetCards;